name: datadog_dio_interceptor
description: A plugin for use with the DatadogSdk, used to track calls made
  using the Dio package.
version: 1.0.0
homepage: http://datadoghq.com
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  datadog_flutter_plugin: ^2.7.0
  dio: ^5.0.0
  flutter:
    sdk: flutter
  meta: ^1.15.0
  uuid: ^4.0.0

dev_dependencies:
  datadog_common_test:
    path: ../datadog_common_test
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter: null
